language: node_js
node_js:
  - '10.9.0'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
# before_script: node ./scripts/tag-update $TRAVIS_TAG
# after_success: npm run cover
script: npm run test:travis
before_deploy: npm run document
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: documentation
    on:
      branch: master
  - provider: script
    skip-cleanup: true
    script: npm run preapare-and-publish
    on:
      tags: true
